### ISSUE TITLE
Error with some url

### ISSUE THREAD

**Issue by art0007i** [sveken/nicetube#1]
I tried this and it failed. the video is a regular yt vid you can watch it [here](https://www.youtube.com/watch?v=-3cW5RH3bAI)
https://ntna1.sveken.com/reso/Q720P/-3cW5RH3bAI

**Comment by sveken** [comment]
Thanks for the report
This was due to how i was passing the command line arguments and the dash was triggering yt-dlp as an argument. 
Thankfully they provide a work around with https://github.com/yt-dlp/yt-dlp/issues/7618 Which has solved it.

Release 0.5+ should solve it
